### ISSUE TITLE
What problem does this solve?

### ISSUE THREAD

**Issue by faho** [fishery/available#2]
Hi, I don't quite get what this is made for, considering fish already ships `type`, which has a "-q" option (and has for quite some time).

What does this do better?

**Comment by bucaran** [comment]
Nothing. It's a survivor of the Wahoo era inherited by OMF and exists only to support OMF plugins that still use it. It's unfortunate. I provided some [notes](https://github.com/fishery/available#notes) in the README to educate users stumbling upon this about the alternatives.

**Comment by faho** [comment]
>I provided some notes in the README to educate users stumbling upon this about the alternatives.

Still missing `type -q`, though - then you don't need to silence stdout and stderr manually.

**Comment by bucaran** [comment]
Good point.

b39d814c91105286a1ad810cd0302fbeb962387e
